//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarmyKnife.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarmyKnife.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   StarmyKnife に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChainConverter_AutoConvertCheckBoxLabel {
            get {
                return ResourceManager.GetString("ChainConverter_AutoConvertCheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChainConverter_ClearInputButton {
            get {
                return ResourceManager.GetString("ChainConverter_ClearInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChainConverter_ConvertButton {
            get {
                return ResourceManager.GetString("ChainConverter_ConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChainConverter_ResetPluginBoxesButton {
            get {
                return ResourceManager.GetString("ChainConverter_ResetPluginBoxesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChainConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChainConverterPageTitle {
            get {
                return ResourceManager.GetString("ChainConverterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_BulletMark {
            get {
                return ResourceManager.GetString("Common_BulletMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_CopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("Common_CopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_CopyToClipboard {
            get {
                return ResourceManager.GetString("Common_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be greater than or equals to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_MustBeGreaterThanOrEqualsTo {
            get {
                return ResourceManager.GetString("Common_MustBeGreaterThanOrEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_NoParameters {
            get {
                return ResourceManager.GetString("Common_NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error has been occurred: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_UnexpectedErrorHasBeenOccurred {
            get {
                return ResourceManager.GetString("Common_UnexpectedErrorHasBeenOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Csql に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CsqlPageTitle {
            get {
                return ResourceManager.GetString("CsqlPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has been occurred while generating string: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generator_ErrorWhileGeneratingString {
            get {
                return ResourceManager.GetString("Generator_ErrorWhileGeneratingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generator_GenerateButton {
            get {
                return ResourceManager.GetString("Generator_GenerateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of generation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generator_NumberOfGeneration {
            get {
                return ResourceManager.GetString("Generator_NumberOfGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneratorPageTitle {
            get {
                return ResourceManager.GetString("GeneratorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_ClearInputButton {
            get {
                return ResourceManager.GetString("ListConverter_ClearInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_ColumnInput {
            get {
                return ResourceManager.GetString("ListConverter_ColumnInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_ColumnOutput {
            get {
                return ResourceManager.GetString("ListConverter_ColumnOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_ConvertButton {
            get {
                return ResourceManager.GetString("ListConverter_ConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_CopyToClipboardButton {
            get {
                return ResourceManager.GetString("ListConverter_CopyToClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_SetFromClipboardButton {
            get {
                return ResourceManager.GetString("ListConverter_SetFromClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_Tab_Converter {
            get {
                return ResourceManager.GetString("ListConverter_Tab_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input / Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverter_Tab_InputOutput {
            get {
                return ResourceManager.GetString("ListConverter_Tab_InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListConverterPageTitle {
            get {
                return ResourceManager.GetString("ListConverterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidator_ExecButton {
            get {
                return ResourceManager.GetString("PrettyValidator_ExecButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidator_ModeMinify {
            get {
                return ResourceManager.GetString("PrettyValidator_ModeMinify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prettify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidator_ModePrettify {
            get {
                return ResourceManager.GetString("PrettyValidator_ModePrettify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidator_ModeValidate {
            get {
                return ResourceManager.GetString("PrettyValidator_ModeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syntax OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidator_SyntaxOK {
            get {
                return ResourceManager.GetString("PrettyValidator_SyntaxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrettyValidator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrettyValidatorPageTitle {
            get {
                return ResourceManager.GetString("PrettyValidatorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StarmyKnife is a utility that performs various operations on strings (conversion, generation, validation, etc.). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable auto convert by default (take effect after restart) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageChainConverterEnableAutoConvertByDefault {
            get {
                return ResourceManager.GetString("SettingsPageChainConverterEnableAutoConvertByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChainConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageChainConverterTitle {
            get {
                return ResourceManager.GetString("SettingsPageChainConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on output text box to copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageGeneralClickOutputToCopy {
            get {
                return ResourceManager.GetString("SettingsPageGeneralClickOutputToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageGeneralTitle {
            get {
                return ResourceManager.GetString("SettingsPageGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personalization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use PrettyValidator as Converter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageUsePrettyValidatorAsConverter {
            get {
                return ResourceManager.GetString("SettingsPageUsePrettyValidatorAsConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChainConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellChainConverterPage {
            get {
                return ResourceManager.GetString("ShellChainConverterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Csql に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellCsqlPage {
            get {
                return ResourceManager.GetString("ShellCsqlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellGeneratorPage {
            get {
                return ResourceManager.GetString("ShellGeneratorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open or close navigation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellListConverterPage {
            get {
                return ResourceManager.GetString("ShellListConverterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrettyValidator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPrettyValidatorPage {
            get {
                return ResourceManager.GetString("ShellPrettyValidatorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *PathFinder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellXPathFinderPage {
            get {
                return ResourceManager.GetString("ShellXPathFinderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search results に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XPathFinder_LabelSearchResults {
            get {
                return ResourceManager.GetString("XPathFinder_LabelSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XPathFinder_SearchButton {
            get {
                return ResourceManager.GetString("XPathFinder_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *PathFinder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XPathFinderPageTitle {
            get {
                return ResourceManager.GetString("XPathFinderPageTitle", resourceCulture);
            }
        }
    }
}
